### ISSUE TITLE
Connect to server from Putty/TeraTerm not working

### ISSUE THREAD

**Issue by notofug** [microsoft/dev-tunnels-ssh#49]
I have made a custom ssh-server based on this library and the example here ; https://github.com/microsoft/dev-tunnels-ssh/tree/main/src/cs/Ssh#server-example

It works just fine when connecting with openssh ;
![image](https://user-images.githubusercontent.com/40484721/231997634-85dd2d04-ccd2-4fb1-a3f4-4660e134be27.png)

Putty and TeraTerm however does not like the hostkey it seems;
![image](https://user-images.githubusercontent.com/40484721/232000398-0335232e-b47e-4804-afc2-b4aad1601225.png)

Tera Term ; 
![image](https://user-images.githubusercontent.com/40484721/231999953-edf2b3a3-bb4c-4115-bfa1-a1ebac5ec65b.png)

**Comment by notofug** [comment]
- server-log when openssh connects

trace:SshServer Information: 9151 : trace:SshServer client connected.
trace:SshServer Verbose: 9114 : trace:SshServerSession:20974680 ConnectAsync
trace:SshServer Verbose: 9100 : trace:Local version: SSH-2.0-Microsoft.DevTunnels.Ssh_3.11, remote version: SSH-2.0-OpenSSH_for_Windows_8.1
trace:SshServer Verbose: 9101 : trace:Sending #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9102 : trace:Receiving #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9170 : trace:KeyExchange negotiation: Server (ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group16-sha512, diffie-hellman-group14-sha256) Client (curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1, ext-info-c) => ecdh-sha2-nistp256
trace:SshServer Verbose: 9170 : trace:PublicKey negotiation: Server (rsa-sha2-512, rsa-sha2-256) Client (rsa-sha2-512-cert-v01@openssh.com, rsa-sha2-256-cert-v01@openssh.com, ssh-rsa-cert-v01@openssh.com, rsa-sha2-512, rsa-sha2-256, ssh-rsa, ecdsa-sha2-nistp256-cert-v01@openssh.com, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp521-cert-v01@openssh.com, ssh-ed25519-cert-v01@openssh.com, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-ed25519) => rsa-sha2-512
trace:SshServer Verbose: 9170 : trace:ClientEncryption negotiation: Server (aes256-gcm@openssh.com, aes256-cbc, aes256-ctr) Client (chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com) => aes256-ctr
trace:SshServer Verbose: 9170 : trace:ServerEncryption negotiation: Server (aes256-gcm@openssh.com, aes256-cbc, aes256-ctr) Client (chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com) => aes256-ctr
trace:SshServer Verbose: 9170 : trace:ClientHmac negotiation: Server (hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-256) Client (umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1) => hmac-sha2-256-etm@openssh.com
trace:SshServer Verbose: 9170 : trace:ServerHmac negotiation: Server (hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-256) Client (umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1) => hmac-sha2-256-etm@openssh.com
trace:SshServer Verbose: 9170 : trace:ClientCompression negotiation: Server (none) Client (none, zlib@openssh.com, zlib) => none
trace:SshServer Verbose: 9170 : trace:ServerCompression negotiation: Server (none) Client (none, zlib@openssh.com, zlib) => none
trace:SshServer Verbose: 9102 : trace:Receiving #1 KeyExchangeDhInitMessage
trace:SshServer Verbose: 9101 : trace:Sending #1 KeyExchangeDhReplyMessage
trace:SshServer Verbose: 9101 : trace:Sending #2 NewKeysMessage
trace:SshServer Verbose: 9102 : trace:Receiving #2 NewKeysMessage
trace:SshServer Verbose: 9101 : trace:Sending #3 ExtensionInfoMessage(open-channel-request@microsoft.com; server-sig-algs=rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256)
trace:SshServer Verbose: 9110 : trace:SshServerSession:20974680 encrypted
trace:SshServer Verbose: 9102 : trace:Receiving #3 ServiceRequestMessage(Service: ssh-userauth)
trace:SshServer Verbose: 9101 : trace:Sending #4 ServiceAcceptMessage(Service: ssh-userauth)
trace:SshServer Verbose: 9102 : trace:Receiving #4 AuthenticationRequestMessage(Method: none, Username: username)
trace:SshServer Verbose: 9111 : trace:SshServerSession:20974680 Authenticating(Username: username, Key: password)
trace:SshServer Verbose: 9112 : trace:ClientNone authentication succeeded.
trace:SshServer Verbose: 9101 : trace:Sending #5 AuthenticationSuccessMessage
trace:SshServer Verbose: 9102 : trace:Receiving #5 ChannelOpenMessage(ChannelType: session, SenderChannel: 0)
trace:SshServer Verbose: 9101 : trace:Sending #6 ChannelOpenConfirmationMessage(RecipientChannel: 0)(SenderChannel: 0)
trace:SshServer Verbose: 9120 : trace:SshServerSession:20974680 OnChannelOpenCompleted(SshChannel(Type: session, Id: 0, RemoteId: 0))
trace:SshServer Verbose: 9102 : trace:Receiving #6 ChannelRequestMessage(RecipientChannel: 0)(RequestType: pty-req)
trace:SshServer Verbose: 9101 : trace:Sending #7 ChannelSuccessMessage(RecipientChannel: 0)
trace:SshServer Verbose: 9102 : trace:Receiving #7 ChannelRequestMessage(RecipientChannel: 0)(RequestType: shell)
trace:SshServer Verbose: 9101 : trace:Sending #8 ChannelSuccessMessage(RecipientChannel: 0)

**Comment by notofug** [comment]
- server-log when putty (fails to) connect

trace:SshServer Information: 9151 : trace:SshServer client connected.
trace:SshServer Verbose: 9114 : trace:SshServerSession:12954770 ConnectAsync
trace:SshServer Verbose: 9101 : trace:Sending #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9100 : trace:Local version: SSH-2.0-Microsoft.DevTunnels.Ssh_3.11, remote version: SSH-2.0-PuTTY_Release_0.78
trace:SshServer Verbose: 9102 : trace:Receiving #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9170 : trace:KeyExchange negotiation: Server (ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group16-sha512, diffie-hellman-group14-sha256) Client (sntrup761x25519-sha512@openssh.com, curve448-sha512, curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group18-sha512, diffie-hellman-group17-sha512, diffie-hellman-group16-sha512, diffie-hellman-group15-sha512, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1, rsa2048-sha256, rsa1024-sha1, diffie-hellman-group1-sha1, ext-info-c) => ecdh-sha2-nistp256
trace:SshServer Verbose: 9170 : trace:PublicKey negotiation: Server (rsa-sha2-512, rsa-sha2-256) Client (rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-ed448, ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-dss) => rsa-sha2-512
trace:SshServer Verbose: 9170 : trace:ClientEncryption negotiation: Server (aes256-gcm@openssh.com, aes256-cbc, aes256-ctr) Client (aes256-ctr, aes256-cbc, rijndael-cbc@lysator.liu.se, aes192-ctr, aes192-cbc, aes128-ctr, aes128-cbc, chacha20-poly1305@openssh.com, aes128-gcm@openssh.com, aes256-gcm@openssh.com, 3des-ctr, 3des-cbc, blowfish-ctr, blowfish-cbc, arcfour256, arcfour128) => aes256-ctr
trace:SshServer Verbose: 9170 : trace:ServerEncryption negotiation: Server (aes256-gcm@openssh.com, aes256-cbc, aes256-ctr) Client (aes256-ctr, aes256-cbc, rijndael-cbc@lysator.liu.se, aes192-ctr, aes192-cbc, aes128-ctr, aes128-cbc, chacha20-poly1305@openssh.com, aes128-gcm@openssh.com, aes256-gcm@openssh.com, 3des-ctr, 3des-cbc, blowfish-ctr, blowfish-cbc, arcfour256, arcfour128) => aes256-ctr
trace:SshServer Verbose: 9170 : trace:ClientHmac negotiation: Server (hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-256) Client (hmac-sha2-256, hmac-sha1, hmac-sha1-96, hmac-md5, hmac-sha2-256-etm@openssh.com, hmac-sha1-etm@openssh.com, hmac-sha1-96-etm@openssh.com, hmac-md5-etm@openssh.com) => hmac-sha2-256
trace:SshServer Verbose: 9170 : trace:ServerHmac negotiation: Server (hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-256) Client (hmac-sha2-256, hmac-sha1, hmac-sha1-96, hmac-md5, hmac-sha2-256-etm@openssh.com, hmac-sha1-etm@openssh.com, hmac-sha1-96-etm@openssh.com, hmac-md5-etm@openssh.com) => hmac-sha2-256
trace:SshServer Verbose: 9170 : trace:ClientCompression negotiation: Server (none) Client (none, zlib, zlib@openssh.com) => none
trace:SshServer Verbose: 9170 : trace:ServerCompression negotiation: Server (none) Client (none, zlib, zlib@openssh.com) => none
trace:SshServer Verbose: 9102 : trace:Receiving #1 KeyExchangeDhInitMessage
trace:SshServer Verbose: 9101 : trace:Sending #1 KeyExchangeDhReplyMessage
trace:SshServer Verbose: 9101 : trace:Sending #2 NewKeysMessage
trace:SshServer Verbose: 9001 : trace:System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

**Comment by notofug** [comment]
- server-log when tera-term (fails to) connect

trace:SshServer Information: 9151 : trace:SshServer client connected.
trace:SshServer Verbose: 9114 : trace:SshServerSession:399557 ConnectAsync
trace:SshServer Verbose: 9101 : trace:Sending #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9100 : trace:Local version: SSH-2.0-Microsoft.DevTunnels.Ssh_3.11, remote version: SSH-2.0-TTSSH/2.92 Win32
trace:SshServer Verbose: 9102 : trace:Receiving #0 KeyExchangeInitMessage
trace:SshServer Verbose: 9170 : trace:KeyExchange negotiation: Server (ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group16-sha512, diffie-hellman-group14-sha256) Client (ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group18-sha512, diffie-hellman-group16-sha512, diffie-hellman-group14-sha256, diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1) => ecdh-sha2-nistp256
trace:SshServer Error: 9006 : trace:Microsoft.DevTunnels.Ssh.SshConnectionException: Failed PublicKey negotiation: Server (rsa-sha2-512, rsa-sha2-256) Client (ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-ed25519, ssh-rsa, ssh-dss)
Reason: KeyExchangeFailed
   at Microsoft.DevTunnels.Ssh.Services.KeyExchangeService.ChooseAlgorithm(String label, IEnumerable`1 localAlgorithms, IEnumerable`1 remoteAlgorithms)
   at Microsoft.DevTunnels.Ssh.Services.KeyExchangeService.HandleMessageAsync(KeyExchangeInitMessage message, CancellationToken cancellation)
   at Microsoft.DevTunnels.Ssh.SshSession.HandleMessageAsync(KeyExchangeMessage message, CancellationToken cancellation)
   at Microsoft.DevTunnels.Ssh.SshSession.ReceiveAndHandleOneMessageAsync(CancellationToken cancellation)
trace:SshServer Verbose: 9113 : trace:SshServerSession:399557 Close(KeyExchangeFailed, Failed PublicKey negotiation: Server (rsa-sha2-512, rsa-sha2-256) Client (ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-ed25519, ssh-rsa, ssh-dss)
Reason: KeyExchangeFailed)
trace:SshServer Verbose: 9101 : trace:Sending #1 DisconnectMessage(Reason: KeyExchangeFailed, Description: Failed PublicKey negotiation: Server (rsa-sha2-512, rsa-sha2-256) Client (ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-ed25519, ssh-rsa, ssh-dss)
Reason: KeyExchangeFailed)

**Comment by notofug** [comment]
I dont know if this key-problem is with this library or with the clients so any help would be appreciated.
FWIW : When running same scenario with server build on https://github.com/Aimeast/FxSsh all 3 test-clients connect fine.

**Comment by notofug** [comment]
Update : With key generated with one of SshAlgorithms.PublicKey.ECD* algorithms TeraTerm is happy (Putty still objects)
